name: Build APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ArtemSBulgakov/buildozer-action@v1.2.0
    - uses: actions/upload-artifact@v4
      with:
        name: hola-app
        path: bin/*.apk
